
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("NOIDS_DB_HOST") { "127.0.0.1" } %>
  pool: 5
  username: <%= ENV.fetch("NOIDS_DB_USER") { "noid" } %>
  password: <%= ENV.fetch("NOIDS_DB_PASSWORD") { "password" }%>

development:
  <<: *default
  database: noids_development

test:
  <<: *default
  database: noids_test

# production:
#   <<: *default
#   database: noids
