
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("NOIDS_DB_HOST") { "127.0.0.1" } %>
  pool: 5
  username: <%= ENV.fetch("NOIDS_DB_USER") { "noid" } %>
  password: <%= ENV.fetch("NOIDS_DB_PASSWORD") { "password" }%>

development:
  <<: *default
  database: noids

test:
  <<: *default
  database: noids_test

production:
  <<: *default
  host: <%= ENV["NOIDS_DB_HOST"] || "localhost" %>
  database: <%= ENV["NOIDS_DB_NAME"] %>
  username: <%= ENV["NOIDS_DB_USER"] %>
  password: <%= ENV["NOIDS_DB_PASSWORD"] %>
  timeout: 5000
