name: Lint and Test

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch: {}
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RAILS_ENV: test

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ruby-version: ['3.4']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Lint
        run: |
          bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ruby-version: ['3.4']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Setup Postgres
        uses: ikalnytskyi/action-setup-postgres@v7
        with:
          username: noid
          password: password
          database: noids_test

      - name: Setup database
        run: bundle exec rails db:schema:load
          
      - name: Run tests
        run: |
          bundle exec rake
